const texts = {
  invalid_login_title: 'Erreur',
  invalid_login_message:
    "Vous n'avez pas encore de compte NOOBA. Vous devez créer votre compte pour pouvoir accéder à l'application.",
  invalid_login_server_error_title: 'Erreur',
  invalid_login_server_error_text: 'Erreur de connexion au serveur',
  invalid_register_account_exists_title: 'Erreur',
  invalid_register_account_exists_text:
    'Vous êtes déjà inscrit(e) sur NOOBA. Veuillez vous connecter.',
  invalid_validation_activation_code_title: 'Erreur',
  invalid_validation_activation_code_text: "Code d'activation invalide",
  activation_code_resent_title: 'OK',
  activation_code_resent_text: 'Email renvoyé',
  invalid_input_title: 'Erreur',
  invalid_input_text: 'Informations incorrectes',
  invalid_email_title: 'Erreur',
  invalid_email_text: 'Adresse e-mail incorrecte',
  invalid_pwd_title: 'Erreur',
  invalid_pwd_text: 'Vous avez inséré deux mots de passe différents',
  invalid_Gender_title: 'Erreur',
  invalid_Gender_text: "Vous devez cocher un choix pour passer à l'étape suivante",
  invalid_Birth_title: 'Erreur',
  invalid_Birth_text: "La date de naissance n'est pas valide",
  invalid_Birth18_title: 'Erreur',
  invalid_Birth18_text: 'Vous devez avoir 18 ans pour profiter de NOOBA',
  invalid_Locality_title: 'Erreur',
  invalid_Locality_text: 'Vous devez spécifier votre localité',
  invalid_nameEtablissement_title: 'Erreur',
  invalid_nameEtablissement_text: 'Nom de l’établissement invalide',
  invalid_tva_title: 'Erreur',
  invalid_tva_text: 'Code TVA invalide',
  invalid_locality_search_title: 'Erreur',
  invalid_locality_search_text: 'Vous devez spécifier votre localité',
  invalid_change_password_mismatch_title: 'Erreur',
  invalid_change_password_mismatch_text:
    'Les nouveaux mots de passe saisis ne sont pas identiques.',
  invalid_change_password_code_title: 'Erreur',
  invalid_change_password_code_text: 'Code non valide',
  // event creation
  invalid_event_name_title: 'Erreur',
  invalid_event_name_text: 'Vous devez ajouter un titre à l’évènement pour continuer',
  invalid_event_description_title: 'Erreur',
  invalid_event_description_text: 'Vous devez ajouter une description pour continuer.',
  invalid_event_interests_title: 'Erreur',
  invalid_event_interests_text: 'Vous devez ajouter les intérêts de votre évènement',
  invalid_event_name_badwords_title: 'Erreur',
  invalid_event_name_badwords_text: 'Votre évènement contient des critères discriminants',
  invalid_event_date_title: 'Erreur',
  invalid_event_date_text: "La date de l'évènement n'est pas valide",
  invalid_event_location_title: 'Erreur',
  invalid_event_location_text: "Il faut spécifier l'emplacement de votre évènement",
  invalid_event_type_title: 'Erreur',
  invalid_event_type_text: 'Il faut spécifier le type de votre évènement',
  invalid_event_limit_title: 'Erreur',
  invalid_event_limit_text: 'Vous devez spécifier le nombre de places disponibles',
  invalid_event_age_title: 'Erreur',
  invalid_event_age_text: `Tranche d'age incorrecte`,
  invalid_event_gender_type_title: 'Erreur',
  invalid_event_gender_type_text: 'Vous ne pouvez pas publier cet évènement avec ce public cible',

  invalid_event_promotion_title: 'Erreur',
  invalid_event_promotion_text:
    'Vous devez renseigner le cadeau ou geste commercial que vous ferez à vos participants',
  invalid_Image_title: 'Erreur',
  invalid_Image_text: 'Vous devez ajouter ou sélectionner une image',
  invalid_Alert_title: 'Erreur',
  invalid_Alert_text: 'Veuillez donner un nom à cette alerte',
  dark_orange: '#F15A24',
  balanceErrorTitle: 'Erreur',
  balanceErrorText:
    "Vous n'avez plus assez de jetons. Vous pouvez vous en procurer dans la rubrique 'jetons'. ",
  invalid_event_interests_length_title: 'Erreur',
  invalid_event_interests_length_text: 'Vous pouvez ajouter max 5 intérêts',
  annuler_event_confirmation_title: 'Annuler événement',
  annuler_event_confirmation_text: `Vous voulez vraiment annuler l'événement ?`,
  eventDepasse: 'Erreur',
  eventDepasse: "La date de l'évènement n'est pas valide",
  password_change_success_title: 'Succès',
  password_change_success_text: 'Mot de passe changé avec succès',
  password_change_invalid_password_text: 'Le mot de passe saisi est incorrect.',
  contacteznous_message_success_title: 'Succès',
  contacteznous_message_success_text: 'Merci pour votre message. Nous y répondrons prochainement',
  invalid_signal_reason_title: 'Erreur',
  invalid_signal_reason_text: "Vous devez cocher un choix pour passer à l'étape suivante",
  delete_alert_title: 'Erreur',
  delete_alert_text: 'Vous voulez vraiement supprimer cette alert ?',
  google_maps_API_key: '',
};
export default texts;
