# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)


platform :ios do
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "763X6HH235",
      issuer_id: "fb43ae39-0361-4dbc-a58f-542413dbf922",
      key_filepath: "AuthKey_763X6HH235.p8",
    )
    build_number = latest_testflight_build_number(version: "0.1.1", initial_build_number: 0)
    echo(message: build_number.to_s)
    increment_build_number({build_number: build_number + 1})
    build_app(scheme: "Nooba")
    upload_to_testflight
  end
end
